name: Lint (language-agnostic)
on:
  workflow_call:
    inputs:
      validate-all-codebase: { type: boolean, default: true, required: false }
      default-branch:        { type: string,  default: "main", required: false }
      runner:                { type: string,  default: "ubuntu-latest", required: false }
jobs:
  lint:
    runs-on: ${{ inputs.runner }}
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 0 }
      - name: Super-Linter
        uses: super-linter/super-linter@v8
        env:
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate-all-codebase }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
